### ISSUE TITLE
Hinzufügen eines Devices

### ISSUE THREAD

**Issue by RichardGHopf** [a529987659852/GuntamaticBiostar#4]
Ich habe dein Repository mittels HACS in mein HA frontend integriert.
Leider scheitere ich beim Hinzufügen eines Devices:
![image](https://github.com/a529987659852/GuntamaticBiostar/assets/86560415/3174b95e-0139-47bd-a04f-f08c1ba3be82)
Was muss hier angegeben werden?
Vielen Dank, Richard.

**Comment by a529987659852** [comment]
Hallo Richard,
eigentlich sollte im ersten Feld "IP-Adresse" und im zweiten Feld "API-Key (Bereitgestellt von Guntamatic)" stehen.
IP-Adresse ist denke ich selbsterklärend. 
Den API-Key erhälst du von Guntamatic, wenn du denen ein Formular schickst. Musst du mal nach API-Key auf deren Website suchen.

Viel Erfolg
Andreas

**Comment by RichardGHopf** [comment]
Hallo Andreas,

ja vielen Dank für den Hinweis.
Hab schon einen key und deine HA Integration in mein Frontend eingepflegt.
Super Integration - Kompliment!!!

Dazu eine Frage: wie kann ich die Abfrageintervalle im Python Code anpassen?
Wie du im Anhang siehst, sind manche Abfragen über 2h alt.

Cheers, Richard.

**Comment by a529987659852** [comment]
Hi Richard,
danke für das Lob!

Eigentlich sollte die API jede Minute abgefragt werden. Wenn es zu
Netzwerkproblemen oder Verzögerungen kommt, solltest du das im Home
Assistant Log sehen.
Die Abfragezeit wird im Update-Coordinator gepflegt:
https://github.com/a529987659852/GuntamaticBiostar/blob/8d28ff5843a2254adc578b59428736dfdf84e42d/custom_components/GuntamaticBiostar/__init__.py#L174


Am Di., 19. März 2024 um 15:28 Uhr schrieb Richard G. Hopf <
***@***.***>:

> Hallo Andreas,
>
> ja vielen Dank für den Hinweis.
> Hab schon einen key und deine HA Integration in mein Frontend eingepflegt.
> Super Integration - Kompliment!!!
>
> Dazu eine Frage: wie kann ich die Abfrageintervalle im Python Code
> anpassen?
> Wie du im Anhang siehst, sind manche Abfragen über 2h alt.
>
> Cheers, Richard.
>
>

**Comment by RichardGHopf** [comment]
Hi Andreas,

ich sehe das Intervall mit minutes=1 definiert, aber warum updaten manche
Sensoren zu unterschiedlichen Zeiten? 8 von 16 benutzten Parametern wurden
seit 5h nicht upgedatet, dafür andere in 1, 5, oder 30min Abständen. Liegt
das an den timeouts für die Abfragen?
Du hast für die Updates ein 10s und für das Setzen ein 5s timeout gewählt.
Denkst du es würde helfen, das update timeout von 10s zu erhöhen?

In den logs habe ich nur eine Warnung zur Integration gefunden - siehe
Anhang.

Cheers, Richard.

**Comment by a529987659852** [comment]
Das Updateintervall gilt für den Coordinator, der die Updates der ganzen Integration macht. Es läuft so, dass HA jede Minute die beiden APIs der Guntamatic abruft. Dann werden die Werte auf die verschiedenen Sensoren verteilt.
Und im HA ist es so, dass nur bei einer Änderung des Sensorwerts ein neuer Datenpunkt geschrieben wird. Wenn sich also z.B. 6 h nichts ändert, ist dein Sensorwert eben 6 h alt.
Du solltest bei Sensoren für z.B. Isttemperatur (z.B. Außentemperatur, Kesseltemperatur, Vorlauf-Ist-Temperatur) Änderungen im Minutenbereich sehen.
Bei Sensoren, die Solltemperaturen (z.B. guntamaticbiostar_vorlauf_soll_1) oder das aktuelle Programm (z.B. guntamaticbiostar_programm, guntamaticbiostar_programm_hk1 usw.) anzeigen Änderungen im Stundenbereich oder sogar länger sehen.

Hoffe, dass das für dich als Erklärung passt!

**Comment by RichardGHopf** [comment]
Hallo Andreas
vielen Dank für die Erklärung!
ich hab mir schon gedacht, dass Parameter ohne Änderung auch nicht
upgedatet werden.
Nochmals Chapeau für die tolle Integration - Guntamatic sollte dir Geld
dafür zahlen 👍
Cheers, Richard.

**Comment by a529987659852** [comment]
Danke dir!
Guntamatic bräuchte generell mal ne Beratung, wie man saubere
Schnittstellen aufsetzt, die man anständig abfragen kann :-) Aktuell lauft
die Kommunikation über zwei Interfaces und du musst wissen, an welcher
Stelle welche Daten kommen. Klingt so, als ob man Modbus einfach nach Außen
freigegeben hat. Heutzutage läuft das etwas anders :-)

Am Mi., 20. März 2024 um 09:57 Uhr schrieb Richard G. Hopf <
***@***.***>:

> Hallo Andreas
> vielen Dank für die Erklärung!
> ich hab mir schon gedacht, dass Parameter ohne Änderung auch nicht
> upgedatet werden.
> Nochmals Chapeau für die tolle Integration - Guntamatic sollte dir Geld
> dafür zahlen 👍
> Cheers, Richard.
>
>

**Comment by Tek4Seth** [comment]
Hi,
where can i get the API Key ?
thank you

**Comment by RichardGHopf** [comment]
from Guntamatic directly.

**Comment by Tek4Seth** [comment]
Hi, i try with the API from guntamic ; i can integrate the module but I have a lot of sensors but without any value
What can be the problem? thank you

**Comment by ELBengEL** [comment]
> Ich habe dein Repository mittels HACS in mein HA frontend integriert. Leider scheitere ich beim Hinzufügen eines Devices: ![image](https://private-user-images.githubusercontent.com/86560415/313724490-3174b95e-0139-47bd-a04f-f08c1ba3be82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODY2NDcsIm5iZiI6MTcxMzc4NjM0NywicGF0aCI6Ii84NjU2MDQxNS8zMTM3MjQ0OTAtMzE3NGI5NWUtMDEzOS00N2JkLWEwNGYtZjA4YzFiYTNiZTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDExNDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMDBhNzAxZDg0NzdlNDA5YzFhNjAyYjJlNGRiMzNiNTgxNTkzNmQyZDMwZTE3YzQ0MjQ0NDk3ZDM1N2IwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JPMYzwHAhWsTjjIbvRDt5Oqd3x-10j3d3PU8dJ6Xh9Y) Was muss hier angegeben werden? Vielen Dank, Richard.

Hallo, kannst du mir sagen wie du es zum Laufen gebracht hast? GitHub Addon ist installiert, aber wenn ich versuche das ganze als Blaupause hinzuzufügen in HA, sagt er mir immer, dass die URL Falsch ist. Bin ich bei Blaupausen falsch?

**Comment by Tek4Seth** [comment]
> Hallo, kannst du mir sagen wie du es zum Laufen gebracht hast? GitHub Addon ist installiert, aber wenn ich versuche das ganze als Blaupause hinzuzufügen in HA, sagt er mir immer, dass die URL Falsch ist. Bin ich bei Blaupausen falsch?

Which URL ? ; you need to add IP (local) and API key

**Comment by ELBengEL** [comment]
> > Hallo, kannst du mir sagen wie du es zum Laufen gebracht hast? GitHub Addon ist installiert, aber wenn ich versuche das ganze als Blaupause hinzuzufügen in HA, sagt er mir immer, dass die URL Falsch ist. Bin ich bei Blaupausen falsch?
> 
> Which URL ? ; you need to add IP (local) and API key

Sorry, did a mistake while writing...

I did the Integration, but how do i get to the screen where i have to insert the IP and the Key? What do i have to do?

![grafik](https://github.com/a529987659852/GuntamaticBiostar/assets/167761960/61e36247-df75-439f-9e04-6dddc8f8acef)

**Comment by Tek4Seth** [comment]
> > > Hallo, kannst du mir sagen wie du es zum Laufen gebracht hast? GitHub Addon ist installiert, aber wenn ich versuche das ganze als Blaupause hinzuzufügen in HA, sagt er mir immer, dass die URL Falsch ist. Bin ich bei Blaupausen falsch?
> > 
> > 
> > Which URL ? ; you need to add IP (local) and API key
> 
> Sorry, did a mistake while writing...
> 
> I did the Integration, but how do i get to the screen where i have to insert the IP and the Key? What do i have to do?
> 
> ![grafik](https://private-user-images.githubusercontent.com/167761960/324451341-61e36247-df75-439f-9e04-6dddc8f8acef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODg1ODIsIm5iZiI6MTcxMzc4ODI4MiwicGF0aCI6Ii8xNjc3NjE5NjAvMzI0NDUxMzQxLTYxZTM2MjQ3LWRmNzUtNDM5Zi05ZTA0LTZkZGRjOGY4YWNlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMjE4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjZkZWE4ZmJiNzhmNzA5OTYxNmM4NDMxN2I3ZTg2Y2MwNWVlNjlmMTZjZDAzNmIxYjFhM2UwYWU1NWYwMDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9aSWuWlqCiSCs6Fw4OCWDhpm4pDk5h4-jyTLlZl5gG4)

I don't see what view this is.
I installed like this:
1-add the repo in hacs: custom repo (https://github.com/a529987659852/GuntamaticBiostar)
2-download the package
3-add the integration in HA (parameter -> integration)
when you start the integration you can add the ip and the api key

**Comment by RichardGHopf** [comment]
goto integrations and choose Guntamatic.

**Comment by ELBengEL** [comment]
> > > > Hallo, kannst du mir sagen wie du es zum Laufen gebracht hast? GitHub Addon ist installiert, aber wenn ich versuche das ganze als Blaupause hinzuzufügen in HA, sagt er mir immer, dass die URL Falsch ist. Bin ich bei Blaupausen falsch?
> > > 
> > > 
> > > Which URL ? ; you need to add IP (local) and API key
> > 
> > 
> > Sorry, did a mistake while writing...
> > I did the Integration, but how do i get to the screen where i have to insert the IP and the Key? What do i have to do?
> > ![grafik](https://private-user-images.githubusercontent.com/167761960/324451341-61e36247-df75-439f-9e04-6dddc8f8acef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODg1ODIsIm5iZiI6MTcxMzc4ODI4MiwicGF0aCI6Ii8xNjc3NjE5NjAvMzI0NDUxMzQxLTYxZTM2MjQ3LWRmNzUtNDM5Zi05ZTA0LTZkZGRjOGY4YWNlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMjE4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjZkZWE4ZmJiNzhmNzA5OTYxNmM4NDMxN2I3ZTg2Y2MwNWVlNjlmMTZjZDAzNmIxYjFhM2UwYWU1NWYwMDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9aSWuWlqCiSCs6Fw4OCWDhpm4pDk5h4-jyTLlZl5gG4)
> 
> I don't see what view this is. I installed like this: 1-add the repo in hacs: custom repo (https://github.com/a529987659852/GuntamaticBiostar) 2-download the package 3-add the integration in HA (parameter -> integration) when you start the integration you can add the ip and the api key

I did it like this:

![image](https://github.com/a529987659852/GuntamaticBiostar/assets/167761960/1695ea1a-14be-4c91-a397-89d88be24904)

Done:
![image](https://github.com/a529987659852/GuntamaticBiostar/assets/167761960/088cba67-e17b-4982-85ec-aaf3154b0178)

But in integration, there ist no "Guntamatic".

![image](https://github.com/a529987659852/GuntamaticBiostar/assets/167761960/6c22b88b-64fb-4486-9634-9415c257c048)

Did i miss/forgot a step?

**Comment by a529987659852** [comment]
This is the wrong way. It seems as if you added my repo to the github integration.
You need to do what Tek4Seth explained: Add the repo to HACS and then add the integration.

**Comment by ELBengEL** [comment]
got it ... my mistakte was not doing it  in HACS (didn´t have HACS before :) ) ... i did it in devices - integration

Thank you guys :)
