### ISSUE TITLE
No values

### ISSUE THREAD

**Issue by Tek4Seth** [a529987659852/GuntamaticBiostar#5]
Hi,

i add the integration, I have a lot of sensors but no values
When i go to : http://192.x.x.x/daqdata.cgi i see the values ; the same for http://192.x.x.x/daqdesc.cgi 

![image](https://github.com/a529987659852/GuntamaticBiostar/assets/64869530/b0072e38-0d78-477d-8a9a-5254be0f2ca7)
![image](https://github.com/a529987659852/GuntamaticBiostar/assets/64869530/ba914fe1-d5c7-4b0b-985a-1a49d6e7689e)

what is the problem ?
thank you

**Comment by Tek4Seth** [comment]
Hi, still not working for me

**Comment by a529987659852** [comment]
Hi, can you please check http://192.x.x.x/daqdesc.cgi? I assume that your field labels are in French, right?
In my case, my daqdesc.cgi entries are in German. This is how the integration is programmed.

Again very disappointing to see that Guntamatic has absolutely no clue how to develop an interface that works (--> order of fields, language dependent field names, etc...)

Sorry, but (if I'm correct) I you cannot use the integration the way Guntamatic developed this interface in combination with my implementation.
Andreas

**Comment by Tek4Seth** [comment]
> Hi, can you please check http://192.x.x.x/daqdesc.cgi? I assume that your field labels are in French, right? In my case, my daqdesc.cgi entries are in German. This is how the integration is programmed.
> 
> Again very disappointing to see that Guntamatic has absolutely no clue how to develop an interface that works (--> order of fields, language dependent field names, etc...)
> 
> Sorry, but (if I'm correct) I you cannot use the integration the way Guntamatic developed this interface in combination with my implementation. Andreas

Hi,

it's true I also just saw that the fields were localized . I'll try to change the boiler language to German

br

**Comment by Tek4Seth** [comment]
when i switch to german it s work. 
how can (guntamatic) this be done depending on the language

**Comment by a529987659852** [comment]
To quote myself: "very disappointing to see that Guntamatic has absolutely no clue how to develop an interface that works"

But I'm happy that it works now. Not ideal, but could be a workaround. And you'll learn some German when configuring the heater :-)
Andreas
